services:
  postgres:
    image: postgres:latest
    container_name: zoo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zoo
    ports:
      - "8084:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Utrwalanie danych bazy
    networks:
      - zoo-network  # Przypisanie do własnej sieci

  backend:
    build: ./zooBackend 
    container_name: zoo-backend
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: zoo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8083"
    networks:
      - zoo-network  # Przypisanie do tej samej sieci

  frontend:
    build: ./zooFrontend     
    container_name: zoo-frontend
    ports:
      - "3000:80"                 # mapujemy port 80 w kontenerze na 3000 lokalnie
    networks:
      - zoo-network

volumes:
  postgres_data:
    driver: local  # Lokalny wolumen dla danych bazy

networks:
  zoo-network:
    driver: bridge