pipeline {
    agent any

    environment {
        ACR_NAME = 'myacrjemek'
        ACR_LOGIN_SERVER = "${ACR_NAME}.azurecr.io"
        BACKEND_IMAGE    = 'zoo-backend'
        FRONTEND_IMAGE   = 'zoo-frontend'
        TAG              = 'latest'
    }

    stages {

        stage('Install Docker') { 
            steps {
                script {
                    sh 'apt-get update && apt-get install -y docker.io'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${BACKEND_IMAGE}:${TAG} ./zooBackend"
                sh "docker build -t ${FRONTEND_IMAGE}:${TAG} ./zooFrontend"
            }
        }

        stage('Login to ACR') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'acr-credentials',
                    usernameVariable: 'ACR_USERNAME',
                    passwordVariable: 'ACR_PASSWORD'
                )]) {
                    sh "docker login ${ACR_LOGIN_SERVER} -u $ACR_USERNAME -p $ACR_PASSWORD"
                }
            }
        }

        stage('Tag & Push Image') {
            steps {
                script {
                    def fullTagBackend = "${ACR_LOGIN_SERVER}/${BACKEND_IMAGE}:${TAG}"
                    def fullTagFrontend = "${ACR_LOGIN_SERVER}/${FRONTEND_IMAGE}:${TAG}"
                    sh "docker tag ${BACKEND_IMAGE}:${TAG} ${fullTagBackend}"
                    sh "docker push ${fullTagBackend}"
                    sh "docker tag ${FRONTEND_IMAGE}:${TAG} ${fullTagFrontend}"
                    sh "docker push ${fullTagFrontend}"
                }
            }
        }
    }
}