server {
    listen       80;
    server_name  localhost;

    # Katalog, w którym Nginx bedzie szukał plików (po COPY build/ → /usr/share/nginx/html)
    root   /usr/share/nginx/html;
    index  index.html;

    # 1) Serwujemy normalnie wszystkie pliki statyczne
    location ~* \.(?:css|js|json|jpg|jpeg|gif|png|svg|ico|ttf|woff|woff2)$ {
        try_files $uri =404;
    }

    # 2) Jeśli żądanie nie trafia w powyższy wzorzec (czyli np. /registrar/account, /ws, /inny/ścieżka),
    #    to zwracamy zawsze index.html, aby React-router mógł obsłużyć trasę po stronie klienta.
    location / {
        try_files $uri /index.html;
    }
}
